Feature/si 1215 add wwt
lidofinance/lido-ethereum-sdk pull request #117
Opened 2024-03-21 07:57 UTC by Tarens2

### Description

- added withdrawal waiting time API endpoints integration
  - request time by amount (`/v2/request-time/calculate`)
  - request time by request ids (`/v2/request-time`)
- added examples in playground

### Checklist:

- [x]  Checked the changes locally.
- [x]  Created/updated unit tests.
- [x]  Created/updated README.md.

2024-03-22 06:26 UTC, Jeday requested changes

2024-03-22 06:26 UTC, Jeday commented on packages/sdk/src/withdraw/withdraw-waiting-time.ts
> +        await new Promise((resolve) => setTimeout(resolve, 1000));
We need to pass this request-delay as an optional prop.

2024-03-22 06:26 UTC, Jeday commented on packages/sdk/src/withdraw/withdraw-waiting-time.ts
> +const urls = {
Let's move `urls` this to core/consts

2024-03-22 06:26 UTC, Jeday commented on packages/sdk/src/withdraw/withdraw-waiting-time.ts
> +      urls[this.bus.core.chainId] +
Let's add a way to override url similar to getSubgraph rewards. This will allow users to run SDK on their own instances of APIs or in closed secured environments.

2024-03-22 07:29 UTC, DiRaiks commented on packages/sdk/README.md
> +  - `amount` (Type: bigint): The amount of withdrawable eth.
Can be 0 if needs to get out the time of the current queue

2024-03-22 07:31 UTC, DiRaiks commented on packages/sdk/src/withdraw/types.ts
> +export type RequestInfoDto = {
it is not DTO.
Lets use just `RequestInfo`

2024-03-22 07:32 UTC, DiRaiks commented on packages/sdk/src/withdraw/types.ts
> +export type RequestByIdInfoDto = {
`RequestByIdInfo` for consistency

2024-03-22 07:33 UTC, DiRaiks commented on packages/sdk/src/withdraw/withdraw-waiting-time.ts
> +    const url =
lets use ``

2024-03-22 07:35 UTC, DiRaiks commented on packages/sdk/src/withdraw/withdraw-waiting-time.ts
> +  @Logger('Utils:')
It is not just utils. Lets add a new logger type - `API` and use it

2024-03-22 07:35 UTC, DiRaiks commented on packages/sdk/src/withdraw/withdraw-waiting-time.ts
> +  @Logger('Utils:')
`API`

2024-03-22 15:31 UTC, Tarens2 commented on packages/sdk/README.md
> +  - `amount` (Type: bigint): The amount of withdrawable eth.
0 is not possible, I will make amount optional and leave comment

2024-03-25 09:43 UTC, Jeday submitted a review, later dismissed

2024-03-25 09:43 UTC, Jeday commented on packages/sdk/src/withdraw/withdraw-waiting-time.ts
> +        ? getWqApiURL()
If it is used like this: 
 - change naming to `getCustomApiURL`
 - pass down to this function as args: default url and current chain.

2024-03-25 09:43 UTC, Jeday commented on packages/sdk/src/withdraw/types.ts
> +  getWqApiURL?: () => string;
Reuse typings please.

2024-03-25 09:43 UTC, Jeday commented on packages/sdk/src/withdraw/withdraw-waiting-time.ts
> +    props: WithdrawalWaitingTimeByRequestIdsParams,
Do we need two objects args? I think they can be merged into one easily, but you can separate typings for props and options.

2024-03-25 11:58 UTC, Jeday submitted a review, later dismissed

2024-03-25 14:19 UTC, DiRaiks submitted a review, later dismissed

2024-03-26 11:44 UTC, Jeday requested changes

2024-03-26 11:44 UTC, Jeday commented on packages/sdk/src/withdraw/withdraw-waiting-time.ts
> +      throw new Error(
Use Error helpers from sdk.

2024-03-26 13:12 UTC, Jeday approved these changes

2024-03-26 13:13 UTC, merged