Feature/si 1362 sdk step by step examples
lidofinance/lido-ethereum-sdk pull request #124
Opened 2024-04-17 11:15 UTC by DiRaiks

### Description

Add examples with a description of the calculation and code:
- Rewards

### Demo

### Code review notes

Please check the calculation description and code examples.

### Checklist:

- [x]  Checked the changes locally.
- [ ]  Created/updated unit tests.
- [x]  Created/updated README.md.

2024-04-17 11:28 UTC, Jeday requested changes

2024-04-17 11:28 UTC, Jeday commented on examples/rewards/README.md
> +## Calculating rewards from on-chain without calculating using the formula
just `without using the formula`

2024-04-17 11:28 UTC, Jeday commented on examples/rewards/README.md
> +## Calculating information about rewards from off-chain without calculating using the formula
off-chain is kinda weird, maybe just subgraph

2024-04-17 11:28 UTC, Jeday commented on examples/rewards/src/lastEvent.ts
> +  // Баланс юзера в шарах до ивента
russian

2024-04-17 11:28 UTC, Jeday commented on examples/rewards/src/sabscribeEvent.ts
file name!

2024-04-17 11:28 UTC, Jeday commented on examples/rewards/src/sabscribeEvent.ts
> +  // Баланс юзера в шарах до ивента
russian

2024-04-17 11:46 UTC, Jeday submitted a review, later dismissed

2024-04-17 20:30 UTC, TheDZhon requested changes
Gonna be a huge thing for the integrations struggling with rebaseable token accounting :+1: 

However, I'd suggest to revisit the comments I left to improve the material's clarity as much as possible :pray:

2024-04-17 20:30 UTC, TheDZhon commented on examples/Examples.md
> +
The provided examples are useful to establish robust accounting for the stETH rebaseable token, learn more about [rebases](https://docs.lido.fi/contracts/lido#rebase) and suggested [reward attribution](https://hackmd.io/@lido/rewards-attribution) approaches.

2024-04-17 20:30 UTC, TheDZhon commented on examples/Examples.md
> +- [Calculation based on a specific (last) event](rewards/README.md#last-rebase-event)
```suggestion
- [Example 2. Get rewards accrued with the latest stETH token rebase for the chosen account](rewards/README.md#last-rebase-event)
```

2024-04-17 20:30 UTC, TheDZhon commented on examples/Examples.md
> +- [Calculation information about rewards by on-chain](rewards/README.md#calculating-rewards-from-on-chain-without-calculating-using-the-formula)
```suggestion
- [Examples 3. Retrieve reward history for the chosen account using the event logs (recommended)](rewards/README.md#calculating-rewards-from-on-chain-without-calculating-using-the-formula)
```

2024-04-17 20:30 UTC, TheDZhon commented on examples/Examples.md
> +- [Calculation information about rewards by Subgraph](rewards/README.md#calculating-information-about-rewards-from-off-chain-without-calculating-using-the-formula)
```suggestion
- [Example 4. Retrieve reward history for the chosen account using the Subgraph indexer (alternative way)](rewards/README.md#calculating-information-about-rewards-from-off-chain-without-calculating-using-the-formula)
```

2024-04-17 20:30 UTC, TheDZhon commented on examples/rewards/README.md
> +# Step by step guide to calculate rewards for Rebase event
Let's reshape this doc to answer particular questions as suggested above:
- Example 1. Subscribe on token rebases
- Example 2. Get rewards accrued with the latest rebase
- Example 3. Retrieve the whole history of rewards for the particular account using event logs (recommended)
- Example 4. Retrieve the whole history of rewards for the particular account using the Subgraph indexer (recommended)

Might be interesting to have two additional examples for:
- Example 5. Keep track of rewards accrued for the set of addresses
- Example 6. Calculate the effective APR for the address concerning the given period

2024-04-17 20:30 UTC, TheDZhon commented on examples/Examples.md
> +# Examples
Overall the provided examples have no problem statements to solve :warning: 
Might be just particular cases but still should be formulated in a way 'Example X. How to achieve Y using Z'

2024-04-17 20:30 UTC, TheDZhon commented on examples/rewards/README.md
> +The first thing you need to do is subscribe to the `TokenRebased` event to receive information about the token rebase. As soon as the event is received, it is necessary to calculate the change in the
Might use the following doc: https://hackmd.io/@lido/rewards-attribution

2024-04-17 20:30 UTC, TheDZhon commented on examples/rewards/README.md
> +Although user-friendly, stETH rebases add a whole level of complexity to integrating stETH into other dApps and protocols.
I'd suggest to start with the fact that stETH is a rebaseable token, giving a link to: https://docs.lido.fi/guides/lido-tokens-integration-guide#what-is-steth

2024-04-17 20:30 UTC, TheDZhon commented on examples/rewards/README.md
> +This case can be used to calculate rewards without having to subscribe to a Rebase event.
I didn't get what is the practical problem we solve (suggested my version, but may be wrong)

2024-04-17 20:30 UTC, TheDZhon commented on examples/rewards/README.md
> +## Calculating rewards from on-chain without using the formula
Maybe not 'without using the formula', but 'using the SDK convenience methods'?

2024-04-17 20:30 UTC, TheDZhon commented on examples/rewards/README.md
> +## Calculating information about rewards from subgraph without using the formula
We need to highlight the difference between two methods:
- the first one requires access to the Ethereum RPC API having a full node behind
- the second one requires access to the Subgraph indexers via GraphQL
What are the advantages and disadvantages of both methods?

Also, concerning the review comments above:
- What is the recommended method?
- How to use for batched requests?

2024-04-17 20:30 UTC, TheDZhon commented on examples/rewards/README.md
> +const oldBalanceInShares = await lidoSDK.shares.balance(address);
```suggestion
const balanceInShares = await lidoSDK.shares.balance(address);
```

2024-04-17 20:30 UTC, TheDZhon commented on examples/rewards/README.md
> +  const oldBalanceStETH = (oldBalanceInShares * preTotalEther) / preTotalShares;
```suggestion
  const preBalanceStETH = (balanceInShares * preTotalEther) / preTotalShares;
```

2024-04-17 20:30 UTC, TheDZhon commented on examples/rewards/README.md
> +  const newBalanceStETH =
```suggestion
  const postBalanceStETH =
```

2024-04-17 20:30 UTC, TheDZhon commented on examples/rewards/README.md
> +  // Calculate the user's reward for Rebase Event
might be not rewards but losses as well :warning:

2024-04-17 20:30 UTC, TheDZhon commented on examples/rewards/README.md
> +// User's balance in balls before the event
balls?

2024-04-17 20:30 UTC, TheDZhon commented on examples/rewards/README.md
> +  stepBlock: 10000, // defaults to 50000, max block range per 1 query
can explain that might depend on the RPC capabilities and pricing plans

2024-04-17 20:30 UTC, TheDZhon commented on examples/rewards/README.md
> +    days: 1n,
Compared with the method below, would it mean that this example is only for the last day?

2024-04-19 10:53 UTC, Jeday requested changes

2024-04-19 10:53 UTC, Jeday commented on examples/rewards/README.md
> +Token shares are managed at the contract level, with dedicated methods for handling share-related operations. Detailed documentation on these methods can be found in the [shares-related methods](http
Let's mention and link to SDK docs about shares module

2024-04-19 10:53 UTC, Jeday commented on examples/rewards/README.md
>  [Implementation example](./src/sabscribeEvent.ts)
File name typo

2024-04-19 10:53 UTC, Jeday commented on examples/rewards/README.md
> +  // Calculate user's updated balance per Rebase event
not update balance, but balance change or balance delta

2024-04-19 10:53 UTC, Jeday commented on examples/rewards/README.md
> +  stepBlock: 10000, // max blocks in 1 query - depend on the RPC capabilities and pricing plans
We can  add `includeOnlyRewards:true` and we won't need `if (!reward.apr) return acc;`  below

2024-04-19 10:53 UTC, Jeday commented on examples/rewards/src/averageAPRbyOnChain.ts
> +    stepBlock: 10000, // defaults to 50000, max block range per 1 query
Same as other comment about includeOnlyRewards

2024-04-19 15:54 UTC, DiRaiks commented on examples/rewards/src/averageAPRbyOnChain.ts
> +    address: mockAddress,
Yes, this is the APR for a specific address

2024-04-23 13:21 UTC, TheDZhon approved these changes
LGTM

2024-04-23 13:27 UTC, merged

2024-04-23 15:29 UTC, tyhonchik reviewed
Disclaimer:
I watched Pull Request as a beginner. I didn't test the workability of the examples. Nor have I checked for proper wording, as I may not have enough context expected from the developers on whom this documentation relies.

The documentation is fully described and very detailed. I left a few questions that are non-blocking but would like to clarify.

2024-04-23 15:29 UTC, tyhonchik commented on examples/rewards/src/averageAPRbyOnChain.ts
I suggest putting cross-references in the JSDOC description of the methods (or files), as in the Readme file, where you link to the implementation code.

2024-04-23 15:29 UTC, tyhonchik commented on examples/rewards/src/averageAPRbySubgraph.ts
> +      return `https://gateway-arbitrum.network.thegraph.com/api/[api-key]/subgraphs/id/Sxx812XgeKyzQPaBpR5YZWmGV5fZuBaPdh7DFhzSwiQ`;
Here and in other such examples:
Variables (e.g., from env) are expected based on the documentation in the Readme file. But the current real examples are hardcoded and probably won't work.
Maybe it is better to have a `.env` file with basic parameters like GRAPH_API_KEY and MOCK_ID to make these examples runnable.

2024-04-23 15:29 UTC, tyhonchik commented on examples/rewards/package.json
Since there is a project with dependencies and examples, everything is expected to work out of the box. I suggest adding basic instructions on how to run code samples locally. If the code is not supposed to be runnable, you can remove dependencies and packages so as not to be misleading.

If dependencies and package.json are here for a different purpose, then sorry, the comment is not valid.

2024-04-24 05:24 UTC, Jeday commented on examples/rewards/src/averageAPRbyOnChain.ts
We have plans for separate docs ui on docusaourus and JSDOC also sounds great. But effort/capacity for this project is limited. Will get back to it there is high demand or product value.

2024-04-24 05:26 UTC, Jeday commented on examples/rewards/src/averageAPRbySubgraph.ts
> +      return `https://gateway-arbitrum.network.thegraph.com/api/[api-key]/subgraphs/id/Sxx812XgeKyzQPaBpR5YZWmGV5fZuBaPdh7DFhzSwiQ`;
Those are PAID services and we cannot embed api keys. I agree though we should have used ${} to make it clear that variable is external.

2024-04-24 05:36 UTC, Jeday commented on examples/rewards/package.json
Good point, code is supposed to be runnable but not quite there yet. We used local setup to make sure examples are valid.

2024-04-24 05:38 UTC, Jeday commented on examples/rewards/README.md
> +  // from: {
There are detailed docs for this method in main readme.