Feature/si 827 apr
lidofinance/lido-ethereum-sdk pull request #36
Opened 2023-09-27 14:10 UTC by DiRaiks

### Description

Add:
- statistics (last apr, sma apr)
- events (last rebase events data)

### Demo

<img width="616" alt="image" src="https://github.com/lidofinance/lido-ethereum-sdk/assets/20888859/6a69da6a-d8f1-495c-b09c-78ac24ad6f93">
<img width="579" alt="image" src="https://github.com/lidofinance/lido-ethereum-sdk/assets/20888859/73b2933e-3861-41fc-b9f2-8182002432cb">

### Checklist:

- [x]  Checked the changes locally.
- [ ]  Created/updated unit tests.
- [x]  Created/updated README.md.

2023-09-27 14:34 UTC, solidovic commented on packages/sdk/src/events/events.ts
> +
for what empty line here? looks like we can group '../<>' imports

2023-09-27 14:50 UTC, solidovic commented on packages/sdk/src/events/stethEvents.ts
> +  public async getLastBlock() {
looks like a function returns some value, but type is unclear

2023-09-27 14:50 UTC, solidovic commented on packages/sdk/src/events/stethEvents.ts
> +  public async getBlockByDays(props: { days: number }) {
looks like a function returns some value, but type is unclear

2023-09-27 14:57 UTC, solidovic commented on packages/sdk/src/events/stethEvents.ts
> +import {
looks like `import type {...} ...` much better that `import { type... }` 'cause second one way assumes using `inline type qualifiers`, other words using `import { type SomeType, SomeThing }` but this not using

2023-09-27 15:03 UTC, solidovic commented on packages/sdk/src/statistics/apr.ts
> +    invariant(preTotalEther, 'preTotalEther is not defined');
looks like all fields in props should be required, or it was done that way on purpose (please tell me if this is so)

2023-09-27 15:05 UTC, solidovic commented on packages/sdk/src/events/stethEvents.ts
> +      event: StethEventsAbi[8],
8 looks like magic value

2023-09-27 15:36 UTC, DiRaiks commented on packages/sdk/src/events/stethEvents.ts
> +  public async getLastBlock() {
Here a complex type of slot. Slot auto-detection is enough

2023-09-27 15:36 UTC, DiRaiks commented on packages/sdk/src/events/stethEvents.ts
> +  public async getBlockByDays(props: { days: number }) {
https://github.com/lidofinance/lido-ethereum-sdk/pull/36#discussion_r1338804000

2023-09-27 15:37 UTC, DiRaiks commented on packages/sdk/src/events/stethEvents.ts
> +  public async getLastRebaseEvent() {
https://github.com/lidofinance/lido-ethereum-sdk/pull/36#discussion_r1338804301

2023-09-27 15:39 UTC, DiRaiks commented on packages/sdk/src/statistics/apr.ts
> +    invariant(preTotalEther, 'preTotalEther is not defined');
The fields are optional in the event itself. Therefore, it is easier to check them in the place where they are used

2023-09-27 15:40 UTC, DiRaiks commented on packages/sdk/src/events/stethEvents.ts
> +      event: StethEventsAbi[8],
This is the event index in the ABI. I'll add a constant to make it clearer

2023-09-27 16:29 UTC, DiRaiks commented on packages/sdk/src/events/stethEvents.ts
> +  public async getLastRebaseEvent() {
added type

2023-09-27 17:42 UTC, solidovic submitted a review, later dismissed
LGTM

2023-10-06 09:15 UTC, Jeday requested changes

2023-10-06 09:15 UTC, Jeday commented on packages/sdk/src/events/stethEvents.ts
> +    if (days > 3) return undefined;
This behavior is not mentioned in readme or anyway clear. I understand it causes a error on free rpcs, so maybe let user decide and leave a warning?

2023-10-06 09:15 UTC, Jeday commented on packages/sdk/src/events/stethEvents.ts
> +    if (logs.length === 0) return this.getLastRebaseEvent(days + 1);
I think this might cause infinite recursion in some edge cases.

2023-10-06 09:15 UTC, Jeday commented on packages/sdk/src/events/types.ts
> +export type RebaseEvent = {
Can we extract this type from ABI?

2023-10-06 09:19 UTC, DiRaiks commented on packages/sdk/src/events/stethEvents.ts
> +const BLOCKS_BY_DAY = 7600n;
No, this is an approximate value.

2023-10-06 09:20 UTC, DiRaiks commented on packages/sdk/src/events/stethEvents.ts
> +    if (days > 3) return undefined;
This is not a solution to the problem with free RPS. Here the requests go through recursion until they hit the limit of 3 days. There is a possibility that we will not find an event for the last day and we need to look at the next one

2023-10-06 09:21 UTC, DiRaiks commented on packages/sdk/src/events/stethEvents.ts
> +    if (logs.length === 0) return this.getLastRebaseEvent(days + 1);
This is precisely why there is a condition with a 3-day limit.

2023-10-06 09:22 UTC, DiRaiks commented on packages/sdk/src/events/types.ts
> +export type RebaseEvent = {
I think not, because we don’t have a typechain now

2023-10-06 10:13 UTC, Jeday approved these changes

2023-10-06 10:13 UTC, merged