Rewards&Events improvement
lidofinance/lido-ethereum-sdk pull request #52
Opened 2023-10-27 12:45 UTC by Jeday

### Description

- [ ] alternative props for rewards/events - days range, timestampts
- [ ] Only rewards 
- [ ] Rewards APR - research
- [ ] need extra requests to get apr for every event in rewards history, but for rebase can be calculated easy using helper from APR module
- [ ] Cumulative Rewards

### Checklist:

- [x]  Checked the changes locally.
- [ ]  Created/updated unit tests.
- [ ]  Created/updated README.md.

2023-10-30 10:23 UTC, DiRaiks commented on packages/sdk/src/core/core.ts
> +      const date = (BigInt(Date.now()) - arg.days * 86400000n) / 1000n;
Lets move numbers to constants

2023-10-30 10:24 UTC, DiRaiks commented on packages/sdk/src/events/steth-events.ts
> +          event: StethEventsAbi[8],
Why do you delete the const for ABI index? Lets move to const

2023-10-30 11:21 UTC, DiRaiks requested changes
Discussed in DM

2023-10-31 08:51 UTC, DiRaiks commented on packages/sdk/src/rewards/rewards.ts
> +    if (!includeOnlyRebases) {
It might make sense to skip for items in the previous iteration if only rewards are selected, instead of iterating over the same array several times

2023-10-31 08:51 UTC, DiRaiks commented on packages/sdk/src/rewards/rewards.ts
> +    if (!includeOnlyRebases) {
https://github.com/lidofinance/lido-ethereum-sdk/pull/52/files#r1377240548

2023-11-01 06:40 UTC, Jeday commented on packages/sdk/src/rewards/rewards.ts
> +    if (!includeOnlyRebases) {
No, because you need information in them to calculate rewards.

2023-11-01 06:40 UTC, Jeday commented on packages/sdk/src/rewards/rewards.ts
> +    if (!includeOnlyRebases) {
same as other

2023-11-01 07:36 UTC, DiRaiks approved these changes

2023-11-01 07:40 UTC, merged