docs: changelog
lidofinance/lido-ethereum-sdk pull request #85
Opened 2023-12-13 10:28 UTC by Jeday

Added CHANGELOG.md

2023-12-13 11:22 UTC, DiRaiks requested changes

2023-12-13 11:22 UTC, DiRaiks commented on packages/sdk/CHANGELOG.md
> +# 3.0.1
We need a description in the release flow for this file

2023-12-15 07:40 UTC, Jeday commented on packages/sdk/CHANGELOG.md
> +# 3.0.1
Added

2023-12-18 09:46 UTC, DiRaiks approved these changes

2023-12-18 11:00 UTC, merged